services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        volumes:
          - /home/hugo/Desktop/wyze-test/:/record

        environment:
            # [OPTIONAL] Credentials can be set in the WebUI
            # API Key and ID can be obtained from the wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=hugogzzp@gmail.com
            - WYZE_PASSWORD=MDFqZ8YDih+SsUn
            - API_ID=5def5bfb-af66-43a9-863d-2bbf5fa2953b
            - API_KEY=gFF4QenAc10eysSQLVfOH0oPO4R3Ii3ALE4WBGkV9eiQKijHyGx5KyfKbrHQ
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            # WebUI and Stream authentication:
            - WB_AUTH=True # Set to false to disable web and stream auth.
            - WB_USERNAME=hugo
            - WB_PASSWORD=wyzetest
            - TZ=America/Monterrey
            - RECORD_ALL=True

